defaults:
  - _self_
  - /callbacks: [checkpoint_every_n_steps, checkpoint_monitor, learning_rate_monitor, progress_bar]
  - /data: proteinloc_prediction
  - /model: transformer_300M
  - /strategy: ddp
  - /noise: loglinear
  - /lr_scheduler: constant_warmup

mode: train  # train / ppl_eval / sample_eval
diffusion: absorbing_state
parameterization: subs  # subs / d3pm / sedd
time_conditioning: False
T: 0  # 0 (continuous time) / 1000 
subs_masking: False

seed: 1

prediction:
  freeze_backbone: True
  num_heads: 5
  expansion: 1
  dropout: 0.00
  layer_index: 13
  output_dim: 3
  label_names: ['Cytoplasm', 'Nucleus', 'Cell membrane']

sampling:
  predictor: ddpm_cache  # analytic, ddpm, ddpm_cache
  steps: 128
  noise_removal: True
  # TODO(yair): @subham, why aren't these params under `eval`?
  num_sample_batches: 2  # Total samples: `num_gpus` * `loader.eval_batch_size` * num_sample_batches
  num_sample_log: 2
  semi_ar: False
  stride_length: 1
  num_strides: 1

training:
  # ema: 0.9999
  ema: 0
  antithetic_sampling: True
  importance_sampling: False
  sampling_eps: 1e-3
  change_of_variables: False
  finetune_from: null

eval:
  checkpoint_path: ''  # Used to evaluate a checkpoint after training.
  disable_ema: False
  compute_generative_perplexity: False
  perplexity_batch_size: 8
  compute_perplexity_on_sanity: False
  gen_ppl_eval_model_name_or_path: rna  # gpt2-large, meta-llama/Llama-2-7b-hf
  generate_samples: True

optim:
  weight_decay: 0.001
  lr: 0.005
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  min_learning_rate: 0.00003
  num_warmup_steps: 200

trainer:
  _target_: lightning.Trainer
  accelerator: "auto"
  num_nodes: 1
  # devices: ${device_count:}
  devices: 1
  # accumulate_grad_batches: ${div_up:${loader.global_batch_size}, ${eval:${trainer.devices} * ${loader.batch_size} * ${trainer.num_nodes}}}
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  precision: 'bf16-mixed'
  num_sanity_val_steps: 2
  # max_steps: 1_000_000
  max_epochs: 1000
  log_every_n_steps: 10
  limit_train_batches: 1.0   # train on full dataset, can be used to toggle quick run
  limit_val_batches: 1.0     # validate on full dataset, can be used to toggle quick run
  use_distributed_sampler: false
  val_check_interval: 1.0
  enable_checkpointing: true
  enable_progress_bar: true

tensorboard:
  log_dir: ${cwd:}/tensorboard/${data.name}/${now:%Y.%m.%d}/${now:%H%M%S}
  name: $${now:%Y.%m.%d-%H%M%S}
  version: ${.name}_${seed}

hydra:
  run:
    dir: ../outputs/${data.name}/${model.name}/${now:%Y.%m.%d}/${now:%H%M%S}
  job:
    chdir: true

checkpointing:
  # Use custom `save_dir` if, e.g., saving to S3 bucket, otherwise leave this parameter as is
  save_dir: ${cwd:}
  # Note: `checkpoints` path should correspond to `checkpoint_every_n_steps.dirpath`
  resume_from_ckpt: false
  resume_ckpt_path: ${.save_dir}/checkpoints/last.ckpt
