name: tiny-mamba
type: dimamba2
d_model: 512
n_layer: 12
d_intermediate: 1344
attn_layer_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
attn_cfg: 
  num_heads: 8
  causal: True
  qkv_proj_bias: False
  out_proj_bias: False
  use_flash_attn: True
  use_alibi: True
rms_norm: True
residual_in_fp32: True
fused_add_norm: True
pad_vocab_size_multiple: 8
protein_hidden_size: 960
ssm_cfg: null
num_species: 256
