name: tiny-mamba
type: dimamba2
d_model: 256
n_layer: 4
d_intermediate: 672
attn_layer_idx: []
attn_cfg: null
rms_norm: True
residual_in_fp32: True
fused_add_norm: True
pad_vocab_size_multiple: 8
protein_hidden_size: 960
ssm_cfg:
  d_state: 128
  d_conv: 4
  expand: 2
  headdim: 64
  ngroups: 1

